name: Verify Code Quality

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macosx12.0

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: '13.1'
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test --enable-code-coverage -v
      
    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/MatchPackageTests.xctest/Contents/MacOS/MatchPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
